# Generated by Django 2.2.3 on 2020-01-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_audit_penalty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='id_blacklist',
        ),
        migrations.DeleteModel(
            name='Blacklist',
        ),
    ]
