# Generated by Django 2.2.3 on 2020-01-21 09:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200121_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lastaccessed', models.DateTimeField(default=django.utils.timezone.now)),
                ('penaltycount', models.IntegerField(default=0, null=True)),
                ('rulenum', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(max_length=45)),
                ('id_blacklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Blacklist')),
            ],
        ),
    ]
